name: Bulid Blockly

on:
  push:
    branches: [ main ]   # 只在main上push触发部署
    paths-ignore:   # 下列文件的变更不触发部署
      - README.md
      - LICENSE
      - XML/
      - tools/
  # pull_request:
  #   branches: [ main ]

jobs:
  build-production:
# 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest   
    strategy:
      matrix:
        # 配置所需node版本
        node-version: [16.4] 

    # 自动化步骤
    steps:  

    # 第一步，检出仓库副本
    - uses: actions/checkout@v2   

    # 规定node.js版本
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 第二步，安装依赖
    - name: Install dependencies  
      run: npm install

    # 第三步，打包代码
    - name: Build                 
      run: npm run build --if-present

    # 第四步，将项目发布到Github Pages
    - name: Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        # 该workflow需要操作repo，因此需要一个密钥
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # 发布到的分支
        BRANCH: gh-pages
        # 要发布的文件夹
        FOLDER: dist

    # 第五步，上传到Action File
    # - name: Upload Actions File  
    #   uses: actions/upload-artifact@v2.2.4
    #   with:
    #     name: blockly
    #     path: ./dist