
name: blockly
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
  runs-on: ubuntu-latest
  strategy:
  matrix:
  node-version: [16.x]
steps:
  - uses: actions/checkout@v2.3.4
  - name: Use Node.js ${{ matrix.node-version }}
uses: actions/setup-node@v2
with:
  node-version: ${{ matrix.node-version }}
cache: 'npm'
  - run: npm ci
  - run: npm run build --if-present
  - name: 推送到gh-pages分支
  run: git push origin HEAD:{gh-pages}
    - name: Upload Actions File
    uses: actions/upload-artifact@v2.2.4
with:
  name: blockly
  path: ./dist
  - name: 通知GitHub Actions的运行结果
uses: actions/github-script@0.4.0
with:
  script: |
    const { context } = require('@actions/github');
    const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
    const { owner, repo } = context.repo;
    await octokit.issues.create({
      owner,
      repo,
      title: 'GitHub Actions执行完成',
    body: 'Github Actions已成功完成'
    });
- name: 更新gh-pages分支
run: git push origin HEAD:{gh-pages}